config/routes.rb
KarmaCounterApp::Application.routes.draw do

  resources :points, except: [:edit]

  devise_for :users

  root :to => "points#index"

end

app/models/point.rb
class Point < ActiveRecord::Base
  attr_accessible :comment, :cumulative_value, :value
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :points, order: "created_at DESC"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /points
  # GET /points.json
  def index
    @points = current_user.points

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @points }
    end
  end

  # GET /points/1
  # GET /points/1.json
  def show
    @point = current_user.points.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @point }
    end
  end

  # GET /points/new
  # GET /points/new.json
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @point }
    end
  end

  # POST /points
  # POST /points.json
  def create
    previous_point = current_user.points.first
    @point = Point.new(params[:point])
    cumulative_value = previous_point.nil? ? @point.value : previous_point.cumulative_value + @point.value
    @point.cumulative_value = cumulative_value

    respond_to do |format|
      if @point.save
        current_user.points << @point
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render json: @point, status: :created, location: @point }
      else
        format.html { render action: "new" }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KarmaCounterApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>User</th>
      <th>Comment</th>
      <th>Cumulative value</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>
  
  <tbody>
  <% @points.each do |point| %>
    <tr>
      <td><%= point.value %></td>
      <td><%= point.user_id %></td>
      <td><%= point.comment %></td>
      <td><%= point.cumulative_value %></td>
      <td><%= link_to 'Show', point %></td>
      <td><%= link_to 'Destroy', point, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<dl>
  <dt>Value:</dt>
  <dd><%= @point.value %></dd>

  <dt>User:</dt>
  <dd><%= @point.user_id %></dd>

  <dt>Comment:</dt>
  <dd><%= @point.comment %></dd>

  <dt>Cumulative value:</dt>
  <dd><%= @point.cumulative_value %></dd>
</dl>

<%= link_to 'Back', points_path %>